<?php

/**
 * @file
 * D9 Core related code.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function d9_core_preprocess_block(&$variables) {
  // Add cache tags to make sure the block is updated once it's edited.
  $blocks = [
    'block1',
    'block2',
  ];
  if (in_array($variables['elements']['#id'], $blocks)) {
    $variables['#cache']['tags'] = [
      'block_content:' . $variables['content']['#block_content']->id(),
    ];
  }
}
